### ISSUE TITLE
We were unable to process your request to include RG10_4425.csv of FreeCEN00848 into the database

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1185]
RG10_4425.csv for FreeCEN00848 in WRY undefined method `sex' for nil:NilClass, ["/home/apache/hosts/freecen2/production/app/models/search_record.rb:830:in `block in populate_search_names'", "/home/apache/hosts/freecen2/production/app/models/search_record.rb:817:in `each'", "/home/apache/hosts/freecen2/production/app/models/search_record.rb:817:in `each_with_index'", "/home/apache/hosts/freecen2/production/app/models/search_record.rb:817:in `populate_search_names'", "/home/apache/hosts/freecen2/production/app/models/search_record.rb:812:in `populate_search_from_transcript'", "/home/apache/hosts/freecen2/production/app/models/search_record.rb:910:in `transform'", "/home/apache/hosts/freecen2/production/app/models/freecen_csv_entry.rb:2672:in `translate_individual'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_file_incorporate.rb:40:in `block in incorporate_records'",

**Comment by Captainkirkdawson** [comment]
Issue has nothing to do the the sex field; that is the symptom. It crashed because we did not find the freecen_csv_entry

**Comment by Captainkirkdawson** [comment]
A fix has been added.
While doing this it was noted that a failed incorporation left search records which became duplicated on a successful incorporation.
Added code to remove search records created during a failed incorporation.
Deployed to test3 and to production
