### ISSUE TITLE
CSVProc crash

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeCENMigration#1249]
he CSVProcessor crashed please provide the following information to your coordinator to send to the System Administrators
undefined method `|' for "Sicily":String
["/home/apache/hosts/freecen2/production/app/models/freecen_csv_entry.rb:1467:in `validate_individual'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:1138:in `extract_individual_fields'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:982:in `process_data_record'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:945:in `extract_data_line'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:893:in `block in extract_the_data'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:886:in `each'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:886:in `each_with_index'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:886:in `extract_the_data'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:350:in `a_single_csv_file_process'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:81:in `block in activate_project'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:77:in `each'", "/home/apache/hosts/freecen2/production/lib/freecen_csv_processor.rb:77:in `activate_project'", "/home/apache/hosts/freecen2/production/lib/tasks/build.rake:680:in `block (2 levels) in <top (required)>'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `block in execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `each'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:279:in `execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/airbrake-11.0.1/lib/airbrake/rake.rb:19:in `execute'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'", "/usr/local/lib/ruby/2.6/monitor.rb:235:in `mon_synchronize'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:83:in `block in run'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/bin/rake:23:in `load'", "/home/apache/hosts/freecen2/production/vendor/bundle/ruby/2.6/bin/rake:23:in `<main>'"]

**Comment by Captainkirkdawson** [comment]
Code error Used | instead of !; fixed
